Revert "[open][static_analysis] Initializes m_enableBackgroundRun of ApplicationDescription"
:Release Notes:
This reverts commit e585428d32c6ca5507b39d971f5a039f8dfb74fd.

:Detailed Notes:
Compile fails:
| ../git/src/core/ApplicationDescription.h:225:10: error:
| 'ApplicationDescription::m_enableBackgroundRun' will be initialized after [-Werror=reorder]
|      bool m_enableBackgroundRun;
|           ^~~~~~~~~~~~~~~~~~~~~
| ../git/src/core/ApplicationDescription.h:224:10: error:
| 'bool ApplicationDescription::m_handleExitKey' [-Werror=reorder]
|      bool m_handleExitKey;

:Testing Performed:
N/A

:QA Notes:
Test-cases: N/A

:Issues Addressed:

Change-Id: I3594a80ddad22d8f7a169140f989bdd7b37bd01f