[agl] Explicitly link WAM binary with ilmCommon library
Fixes error:
libWebAppMgr.so: undefined reference to `ilm_init'

This seems to be required in master/halibut.

AGL-bug: SPEC-2532

Signed-off-by: Jacobo Aragunde Pérez <jaragunde@igalia.com>