Fix build with gcc-13
:Release Notes:
This affects only the version used in OSE.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/530989

FAILED: src/core/CMakeFiles/WebAppMgrCore.dir/web_process_manager.cc.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DHAS_LTTNG -DTRACE_PROVIDER_LIB_PATH=\"/usr/lib/libWebAppMgrTrace.so.1.0\" -DWebAppMgrCore_EXPORTS -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot/usr/include/webruntime -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src/core -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src -ITOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src/util -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git=/usr/src/debug/wam/1.0.2-71-r53  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git=/usr/src/debug/wam/1.0.2-71-r53  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/build=/usr/src/debug/wam/1.0.2-71-r53  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/build=/usr/src/debug/wam/1.0.2-71-r53  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/recipe-sysroot-native=  -fvisibility-inlines-hidden  -Wno-error=uninitialized -Wno-error=maybe-uninitialized -fno-rtti -fno-exceptions -fpermissive -funwind-tables -std=c++14 -Wno-psabi -DNDEBUG -fPIC -std=gnu++14 -MD -MT src/core/CMakeFiles/WebAppMgrCore.dir/web_process_manager.cc.o -MF src/core/CMakeFiles/WebAppMgrCore.dir/web_process_manager.cc.o.d -o src/core/CMakeFiles/WebAppMgrCore.dir/web_process_manager.cc.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src/core/web_process_manager.cc
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src/core/web_process_manager.cc:17:
TOPDIR/BUILD/work/qemux86_64-webos-linux/wam/1.0.2-71-r53/git/src/core/web_process_manager.h:38:3: error: 'uint32_t' does not name a type
   38 |   uint32_t GetWebProcessProxyID(const ApplicationDescription* desc) const;
      |   ^~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: I22241dd93197f76f9971b0b00abddffd74d29a7c
Reviewed-on: http://gpro.lge.com/c/webosose/wam/+/344826
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Donghyun Kim <donghyun11.kim@lge.com>